background #110e13
foreground #e05a4e
selection_background #4e1623
selection_foreground #e05a4e
url_color #2df49b
cursor #e05a4e

macos_titlebar_color #110e13

active_tab_background #f49b2d
active_tab_foreground #110e13
inactive_tab_background #4e1623
inactive_tab_foreground #d0312f

color0 #110e13
color1 #f49b2d
color2 #2df49b
color3 #86f42d
color4 #f49b2d
color5 #f49b2d
color6 #2d86f4
color7 #e05a4e

color8 #961920
color9 #f49b2d
color10 #2df49b
color11 #86f42d
color12 #f49b2d
color13 #f49b2d
color14 #2d86f4
color15 #f3cf9f