background #110e13
foreground #e0a6a1
selection_background #4e1623
selection_foreground #e0a6a1
url_color #5eeb42
cursor #e0a6a1

macos_titlebar_color #110e13

active_tab_background #f29a2d
active_tab_foreground #110e13
inactive_tab_background #4e1623
inactive_tab_foreground #d08887

color0 #110e13
color1 #eb6042
color2 #5eeb42
color3 #ebc042
color4 #425eeb
color5 #dd42eb
color6 #42ebdd
color7 #e0a6a1

color8 #961920
color9 #eb6042
color10 #5eeb42
color11 #ebc042
color12 #425eeb
color13 #dd42eb
color14 #42ebdd
color15 #f3e2cc