background #141928
foreground #9abbd6
selection_background #4e6e94
selection_foreground #9abbd6
url_color #33b849
cursor #9abbd6

macos_titlebar_color background

active_tab_background #3487cc
active_tab_foreground #141928
inactive_tab_background #4e6e94
inactive_tab_foreground #86adce

color0 #141928
color1 #b8333c
color2 #33b849
color3 #adb833
color4 #336fb8
color5 #8133b8
color6 #3397b8
color7 #9abbd6

color8 #3a85bb
color9 #b8333c
color10 #33b849
color11 #adb833
color12 #336fb8
color13 #8133b8
color14 #3397b8
color15 #eef3f8
