set-option -g default-shell $SHELL
set -g default-terminal "tmux-256color"
set -s set-clipboard on
set -g mouse on
setw -g mode-keys vi
setw -g xterm-keys on
set -s escape-time 10
set -sg repeat-time 600
set -s focus-events on
setw -q -g utf8 on
set-option -g history-limit 100000
set -g base-index 1
setw -g pane-base-index 1
setw -g automatic-rename on
set -g renumber-windows on
set -g set-titles on
set -g display-panes-time 800
set -g display-time 1000
set -g status-interval 10
setw -g monitor-activity off
set -g visual-activity off
set -g visual-bell off
set -g visual-silence off
set -g bell-action none
set-option -sa terminal-overrides ',*:RGB'
set-option -sa terminal-features ',xterm-256color:clipboard'

set -g @resurrect-dir "$tmux_dir/resurrect"
set -g @resurrect-save "S"
set -g @resurrect-restore "R"
set -g @continuum-restore "on"
