###############################################################################
# Display
###############################################################################

bg="#181c20"
fg="#e0e2e8"
red="#ffb1c1"
orange="#ffb598"
yellow="#cfca74"
blue="#a6c8ff"
lblue="#a6c8ff"
green="#91d5ad"
cyan="#82d3e2"
magenta="#dbb9f9"
pink="#dbb9f9"
accent="#9ccbfb"
grey1="#fcfcff"
grey2="#fcfcff"
grey3="#fcfcff"
grey4="#f1f0f4"
grey5="#f1f0f4"
grey6="#f1f0f4"
grey7="#e0e2e8"
grey8="#e0e2e8"
grey9="#c2c7cf"
grey10="#c2c7cf"
grey11="#8c9199"
grey12="#8c9199"
grey13="#323539"
grey13_dark="#323539"
grey14="#323539"
grey15="#272a2f"
grey16="#272a2f"
grey17="#272a2f"
grey18="#181c20"
grey19="#181c20"

set -g @mode_indicator_prefix_prompt " WAIT #[default]#[fg=$green]"
set -g @mode_indicator_prefix_mode_style bg=$green,fg=$bg
set -g @mode_indicator_copy_prompt " COPY #[default]#[fg=$blue]"
set -g @mode_indicator_copy_mode_style bg=$blue,fg=$bg
set -g @mode_indicator_sync_prompt " SYNC #[default]#[fg=$red]"
set -g @mode_indicator_sync_mode_style bg=$red,fg=$bg
set -g @mode_indicator_empty_prompt " TMUX #[default]#[fg=$grey12]"
set -g @mode_indicator_empty_mode_style bg=$grey12,fg=$bg

set -g @route_to_ping "vultr.net"
set -g @online_icon "#[fg=$green]〇"
set -g @offline_icon "#[fg=$red]〇"

set -g status on
set -g status-justify centre
set -g status-position bottom
set -g status-left-length 90
set -g status-right-length 90
set -g status-style "bg=$bg"
set -g window-style "fg=$grey10,bg=$bg"
set -g window-active-style "fg=$fg,bg=$bg"

set -g message-style bg=$accent,fg=$bg
set -g pane-border-style fg=$grey11
set -g pane-active-border-style fg=$accent

set -g popup-style "bg=$bg,fg=$fg"
set -g popup-border-style "fg=$accent"
set -g popup-border-lines rounded
setw -g window-status-separator ""

#################################### FORMAT ####################################
set -g status-left "#{tmux_mode_indicator} "
set -g status-right "#[fg=$grey11]#{online_status}   #[fg=$grey11]%R"

setw -g window-status-format "#[fg=$grey11,nobold,nounderscore,noitalics] #[fg=$grey11] #I #W #[fg=$grey11,nobold,nounderscore,noitalics]"
setw -g window-status-current-format "#[fg=$grey11,nobold,nounderscore,noitalics] #[fg=$accent] #I #W #[fg=$grey11,nobold,nounderscore,noitalics]"