###############################################################################
# Display
###############################################################################

bg="#110e13"
fg="#e0a6a1"
red="#eb6042"
orange="#eb9f42"
yellow="#ebc042"
blue="#425eeb"
lblue="#425eeb"
green="#5eeb42"
cyan="#42ebdd"
magenta="#dd42eb"
pink="#dd42eb"
accent="#f29a2d"
grey1="#f3e2cc"
grey2="#f3e2cc"
grey3="#f3e2cc"
grey4="#f7ddc1"
grey5="#f7ddc1"
grey6="#f7ddc1"
grey7="#e0a6a1"
grey8="#e0a6a1"
grey9="#d08887"
grey10="#d08887"
grey11="#961920"
grey12="#961920"
grey13="#4e1623"
grey13_dark="#4e1623"
grey14="#4e1623"
grey15="#25141b"
grey16="#25141b"
grey17="#25141b"
grey18="#110e13"
grey19="#110e13"

set -g @mode_indicator_prefix_prompt " WAIT #[default]#[fg=$green]"
set -g @mode_indicator_prefix_mode_style bg=$green,fg=$fg
set -g @mode_indicator_copy_prompt " COPY #[default]#[fg=$blue]"
set -g @mode_indicator_copy_mode_style bg=$blue,fg=$fg
set -g @mode_indicator_sync_prompt " SYNC #[default]#[fg=$red]"
set -g @mode_indicator_sync_mode_style bg=$red,fg=$fg
set -g @mode_indicator_empty_prompt " TMUX #[default]#[fg=$grey12]"
set -g @mode_indicator_empty_mode_style bg=$grey12,fg=$grey7

set -g @route_to_ping "vultr.net"
set -g @online_icon "#[fg=$green]〇"
set -g @offline_icon "#[fg=$red]〇"

set -g status on
set -g status-justify centre
set -g status-position bottom
set -g status-left-length 90
set -g status-right-length 90
set -g status-style "bg=$bg"
set -g window-style "fg=$grey10,bg=$bg"
set -g window-active-style "fg=$fg,bg=$bg"

set -g message-style bg=$accent,fg=$bg
set -g pane-border-style fg=$grey11
set -g pane-active-border-style fg=$accent

set -g popup-style "bg=$bg,fg=$fg"
set -g popup-border-style "fg=$accent"
set -g popup-border-lines rounded
setw -g window-status-separator ""

#################################### FORMAT ####################################
set -g status-left "#{tmux_mode_indicator} "
set -g status-right "#[fg=$grey11]#{online_status}   #[fg=$grey11]%R"

setw -g window-status-format "#[fg=$grey11,nobold,nounderscore,noitalics] #[fg=$grey11] #I #W #[fg=$grey11,nobold,nounderscore,noitalics]"
setw -g window-status-current-format "#[fg=$grey11,nobold,nounderscore,noitalics] #[fg=$accent] #I #W #[fg=$grey11,nobold,nounderscore,noitalics]"