gui:
  scrollHeight: 2
  scrollPastBottom: true
  sidePanelWidth: 0.3333
  expandFocusedSidePanel: true
  mainPanelSplitMode: 'flexible'
  language: 'auto'
  theme:
    activeBorderColor:
      - green
    inactiveBorderColor:
      - blue
    optionsTextColor:
      - black
    selectedLineBgColor:
      - reverse
    cherryPickedCommitBgColor:
      - blue
    cherryPickedCommitFgColor:
      - cyan
  commitLength:
    show: false
  mouseEvents: true
  skipDiscardChangeWarning: false
  skipStashWarning: true
  showFileTree: false
  showListFooter: false
  showRandomTip: false
  showCommandLog: false
  commandLogSize: 8
git:
  diffRenderers:
    - colorArg: always
      command: diff-so-fancy
  merging:
    manualCommit: false
    args: ''
  skipHookPrefix: WIP
  autoFetch: true
  branchLogCmd: "git log --graph --color=always --abbrev-commit --date=relative --decorate --date=relative --pretty=medium --oneline {{branchName}} --"
  overrideGpg: false
  disableForcePushing: true
  parseEmoji: true
  allBranchesLogCmds:
    - git log --graph --all --color=always --abbrev-commit --decorate --date=relative  --pretty=medium
refresher:
  refreshInterval: 3
  fetchInterval: 5
update:
  method: background
  days: 1
confirmOnQuit: false
quitOnTopLevelReturn: true
disableStartupPopups: true
notARepository: 'skip'
keybinding:
  universal:
    quit: ['q', '<ctrl+c>']
    return: '<esc>'
    quitWithoutChangingDirectory: 'Q'
    togglePanel: '<tab>'
    prevItem: ['<up>', 'k']
    nextItem: ['<down>', 'j']
    prevPage: ','
    nextPage: '.'
    gotoTop: '<'
    gotoBottom: '>'
    prevBlock: ['<left>', 'h']
    nextBlock: ['<right>', 'l']
    nextMatch: 'n'
    prevMatch: 'N'
    optionMenu: ['x', '?']
    toggleRangeSelect: 'V'
    select: '<space>'
    goInto: '<enter>'
    openRecentRepos: '<ctrl+r>'
    confirm: ['<enter>', 'y']
    remove: 'd'
    new: 'n'
    edit: 'e'
    openFile: 'o'
    scrollUpMain: ['<pgup>', 'K', '<ctrl+u>']
    scrollDownMain: ['<pgdown>', 'J', '<ctrl+d>']
    executeShellCommand: ':'
    createRebaseOptionsMenu: 'm'
    pushFiles: 'P'
    pullFiles: 'p'
    refresh: 'R'
    createPatchOptionsMenu: '<ctrl+p>'
    nextTab: ']'
    prevTab: '['
    nextScreenMode: '+'
    prevScreenMode: '_'
    undo: 'z'
    redo: '<ctrl+z>'
    filteringMenu: '<ctrl+s>'
    diffingMenu: ['W', '<ctrl+e>']
    copyToClipboard: '<ctrl+o>'
    submitEditorText: '<enter>'
    extrasMenu: '@'
    toggleWhitespaceInDiffView: '<ctrl+w>'
  status:
    checkForUpdate: 'u'
    recentRepos: '<enter>'
  files:
    commitChanges: 'c'
    commitChangesWithoutHook: 'w'
    amendLastCommit: 'A'
    commitChangesWithEditor: 'C'
    ignoreFile: 'i'
    refreshFiles: 'r'
    stashAllChanges: 's'
    viewStashOptions: 'S'
    toggleStagedAll: 'a'
    viewResetOptions: 'D'
    fetch: 'f'
    toggleTreeView: '`'
  branches:
    createPullRequest: 'o'
    viewPullRequestOptions: 'O'
    checkoutBranchByName: 'c'
    forceCheckoutBranch: 'F'
    rebaseBranch: 'r'
    mergeIntoCurrentBranch: 'M'
    viewGitFlowOptions: 'i'
    fastForward: 'f'
    pushTag: 'P'
    setUpstream: 'u'
    fetchRemote: 'f'
  commits:
    squashDown: 's'
    renameCommit: 'r'
    renameCommitWithEditor: 'R'
    viewResetOptions: 'g'
    markCommitAsFixup: 'f'
    createFixupCommit: 'F'
    squashAboveCommits: 'S'
    moveDownCommit: '<ctrl+j>'
    moveUpCommit: '<ctrl+k>'
    amendToCommit: 'A'
    pickCommit: 'p'
    revertCommit: 't'
    cherryPickCopy: ['c', 'C']
    setFixupMessage: '<ctrl+f>'
    pasteCommits: 'v'
    tagCommit: 'T'
    checkoutCommit: '<space>'
    resetCherryPick: '<ctrl+x>'
    copyCommitAttributeToClipboard: '<ctrl+y>'
  stash:
    popStash: 'g'
  commitFiles:
    checkoutCommitFile: 'c'
  main:
    toggleSelectHunk: 'a'
    pickBothHunks: 'b'
  submodules:
    init: 'i'
    update: 'u'
    bulkMenu: 'b'
